#!/bin/bash

#
# Parameters:
#
# [nextlinux path]     run backend with custom nextlinux executables path
#

if [ ! -z "$1" ] && [ -e "$1" ]
then
    # or use custom path
    NEXTLINUX_PATH=$1
else
    NEXTLINUX_PATH='../../../sysdig/build/userspace/nextlinux'
fi

run() {
    cd sbom-electron/backend

    npm start --- -p=${NEXTLINUX_PATH}

    cd ../..
}

run
